# Site
repository: anhpham52
favicon: images/favicon.ico

# Personal info
name: Nguyen Quoc Anh Pham
#title:
email: anhpham5293@gmail.com
#website: www.github.com/anhpham52

# Social links
#twitter_username: facespics
github_username:  anhpham52
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: anhpham52
# pinterest_username: jekyll
# youtube_username: anhpham52
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.JPG
about_content: | # this will include new lines to allow paragraphs
  I am a PhD student in Economics at the University of Birmingham. My research mainly focuses on Macro analysis with the use of time-series data and DSGE model. I also have experience in applying programming language such as R and Matlab to deal with data and simulations. Besides, I work as a teaching assistant for Postgraduate taught programmes including International Banking & Finance, Options and Derivatives.


# Projects Section
# projects_title: Research

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme
darkmode: true (options: true, false, never)
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
